apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../../k8s/production/runners/service-accounts.yaml
- ../../../../../k8s/production/runners/namespace.yaml
- ../../../../../k8s/production/runners/public/graviton/2/release.yaml
- ../../../../../k8s/production/runners/public/graviton/3/release.yaml
- ../../../../../k8s/production/runners/public/x86_64/v2/release.yaml
- ../../../../../k8s/production/runners/public/x86_64/v3/release.yaml
- ../../../../../k8s/production/runners/public/x86_64/v4/release.yaml
- ../../../../../k8s/production/runners/public/x86_64/v2-win/release.yaml

patches:
  - target:
      kind: HelmRelease
      name: runner-graviton2-pub
      namespace: gitlab
    patch: |-
      - op: replace
        path: /spec/values/gitlabUrl
        value: https://gitlab.sandbox.spack.io/
      - op: remove
        path: /spec/valuesFrom

  - target:
      kind: HelmRelease
      name: runner-graviton3-pub
      namespace: gitlab
    patch: |-
      - op: replace
        path: /spec/values/gitlabUrl
        value: https://gitlab.sandbox.spack.io/
      - op: remove
        path: /spec/valuesFrom

  - target:
      kind: HelmRelease
      name: runner-x86-v2-pub
      namespace: gitlab
    patch: |-
      - op: replace
        path: /spec/values/gitlabUrl
        value: https://gitlab.sandbox.spack.io/
      - op: remove
        path: /spec/valuesFrom

  - target:
      kind: HelmRelease
      name: runner-x86-v3-pub
      namespace: gitlab
    patch: |-
      - op: replace
        path: /spec/values/gitlabUrl
        value: https://gitlab.sandbox.spack.io/
      - op: remove
        path: /spec/valuesFrom

  - target:
      kind: HelmRelease
      name: runner-x86-v4-pub
      namespace: gitlab
    patch: |-
      - op: replace
        path: /spec/values/gitlabUrl
        value: https://gitlab.sandbox.spack.io/
      - op: remove
        path: /spec/valuesFrom

  - target:
      kind: HelmRelease
      name: runner-x86-v2-pub-windows
      namespace: gitlab
    patch: |-
      - op: replace
        path: /spec/values/gitlabUrl
        value: https://gitlab.sandbox.spack.io/
      - op: remove
        path: /spec/valuesFrom
